# Generated by Django 3.2.18 on 2023-04-21 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='eatured_image',
            new_name='featured_image',
        ),
    ]
